#include"stdlib.h"
#include"conio.h" 
#include"stdio.h"
#include"string.h"
#include"dos.h"

#include"bios.h"
#include"math.h"
#include"time.h"
#include"malloc.h"	
#include"io.h"
#include"ctype.h"
#include"process.h"
#include"fcntl.h"
